import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Layout } from 'antd'
const {Header, Footer, Menu} = Layout


export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <title>Skanfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link
      rel="icon"
      href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>👨‍💻</text></svg>"
    />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Skanfolio
        </h1>


        
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>About &rarr;</h2>
            <p>Learn more about ya boi!</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Projects &rarr;</h2>
            <p>See what i can do 💪</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Method &rarr;</h2>
            <p>Wanna see how I work?</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              i.e. hire me!
            </p>
          </a>
        </div>
      </main>

      
    </div>
  )
}
